name: MyGet version mismatches

on:
  workflow_dispatch:
  schedule:
    # Runs daily at a weird time (02:41 UTC) to avoid delays during periods of
    # high loads of GitHub Actions workflow runs.
    - cron: '41 2 * * *'


jobs:
  update_badge:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Checkout wiki code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
      - name: Update dynamic badge gist
        uses: schneegans/dynamic-badges-action@e9a478b16159b4d31420099ba146cdc50f134483 # v1.7.0
        with:
          auth: ${{ secrets.REPO_TOKEN }}
          gistID: 6b327d35bc5a44f6ae6be95c48be4f8a
          filename: badge.svg
          label: 'MyGet mismatches'
          message: 69
          valColorRange: ${{ env.mismatches }}
          maxColorRange: 1
          minColorRange: 0
          invertColorRange: true
